src/TeachMe/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Mvc;
using TeachMe.Models;
using TeachMe.ViewModels;

namespace TeachMe.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext _context = new ApplicationDbContext();

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        //Return the start view
        public IActionResult Start()
        {
            return View();
        }


       

        public IActionResult Social()
        {

            return View();
        }





        //Show all rewards, Return the RewardsDetails view +Search
        public IActionResult RewardsDetails( string search)
        {

            var rew = _context.Rewards.ToList();

            if (!String.IsNullOrEmpty(search))
            {
                rew = rew.Where(r => r.Title.Contains(search)).ToList();
            }
            return View(rew);
        }


        //chaeck if i can to redirect to student controller

        public IActionResult StudentDetails(string search,string filter)
        {
             ViewData["sc"] = _context.StudentsCourses.ToList();

            var stud = _context.Students.ToList().OrderBy(u => u.FirstName).ToList();
  
            if (!String.IsNullOrEmpty(search))
            {
                stud = stud.Where(s => s.FirstName.Equals(search)).ToList().OrderBy(u => u.FirstName).ToList();
            }
            
            //return View(_context.Students.ToList().OrderBy(s => s.FirstName));

            if (!String.IsNullOrEmpty(filter))
            {
                switch (filter)
                {
                    case "FirstName":
                        stud = stud.OrderBy(u => u.FirstName).ToList();
                        break;
                    case "LastName":
                        stud = stud.OrderBy(u => u.LastName).ToList();
                        break;
                    case "Money":
                        stud = stud.OrderBy(u => u.Jubot).ToList();
                        break;
                    case "Money Per Hour":
                        stud = stud.OrderBy(u => u.JubotPerHour).ToList();
                        break;
                    case "Address":
                        stud = stud.OrderBy(u => u.Address).ToList();
                        break;
                    default:
                        stud = stud.OrderBy(u => u.FirstName).ToList();
                        break;
                }
            }

            return View(stud);
        }

        //Return the Index view
        public IActionResult Index()
        {
            return View();
        }


        //Return the contact view
        public IActionResult Contact()
        {
           
            return View();
        }





        public IActionResult Error()
        {
            return View();
        }


        public IActionResult StudentsGraph()
        {
            return View();
        }

        //Hold the adress of student for studenst map
        public class places
        {
            public string addr { get; set; }
        }


        //Get address of students
        public JsonResult getAddresses()
        {
            List<places> address = new List<places>();

            foreach (var item in _context.Students)
            {
                places place = new places();

                if (!String.IsNullOrEmpty(item.Address))
                {
                    place.addr = item.Address;
                    address.Add(place);
                }
            }
            return Json(address);
        }




        //Return the student map view
        public IActionResult StudentsMap()
        {
            return View();
        }



        /*
        public List<Course> IActionResult(int id)
        {
            var courses = _context.StudentsCourses.Where(s => s.Student.StudentID == id).Select(c => c.Course);
           return ((List<Course>)courses);
        }*/

        
        //Search for review by name , address and jubot per hour
        [HttpPost]
        public IActionResult Search(string Name, string Address, int jubot)
        {
            
            var name = from l in _context.Students
                        where l.FirstName.Equals(Name) && l.Address.Contains(Address) && l.JubotPerHour >= jubot
                       select l;


            if (name == null)
            {

                List<object> BothModels = new List<object>();
                BothModels.Add(_context.Students.ToList());
                BothModels.Add(_context.Reviews.ToList());
                return View("StudentsReview",BothModels);
            }

            else
            {
                List<object> BothModels = new List<object>();
                BothModels.Add(name.ToList());
                BothModels.Add(_context.Reviews.ToList());
                return View("StudentsReview", BothModels);
            }
        }




        //Show all students reviews
        public IActionResult StudentsReview()
        {
            List<object> BothModels = new List<object>();
            BothModels.Add(_context.Students.ToList());
            BothModels.Add(_context.Reviews.ToList());
            return View(BothModels);

        }




        //Insrt Review for student
        public IActionResult InsertReview(string Name, string Revieww, int rate, int StudentID)
        {
            Review review = new Review();


            review.Date = DateTime.Now;  
            review.Name = Name;
            review.Revieww = Revieww;
            review.StudentID = StudentID;
            review.rate = (Rate)rate;
            _context.Reviews.Add(review);
            _context.SaveChanges();
            return RedirectToAction("StudentsReview");
        }





        //Show rewards of student
        public IActionResult showRewards(int id)
        {

            //Find the student by ID
            var stud = _context.Students.SingleOrDefault(x => x.StudentID == id);
            //Get full Name
            ViewBag.Name = stud.FirstName + " " + stud.LastName;
            //Find all the rewards that the user can get
            var result = from reward in _context.Rewards
                         where stud.Jubot >= reward.NumOfJubot
                         select new RewardDet()
                         {
                             RewardName = reward.Title,
                             Picture = reward.Picture,
                             Video = reward.Video,
                         };

         
           
            return View(result);
        }




        //Return the Course Graph
        public IActionResult CoursesGraph()
        {

            return View();
        }


        



        public JsonResult ShowCourses(int id)
        {
            var result = _context.StudentsCourses.Where(s => s.Student.StudentID == id).Select(c => c.Course);


            return Json(result);
        }




        //Hold the values of the CourseGraph
        public class Result
        {
            public string State { get; set; }
            public int freq { get; set; }
        }

        

        //Courses Graph Init
        public JsonResult CoursesGraphInit()
        {

            List<Result> CorsesGraph = new List<Result>();
            //Create table with the courses
            var query = from sc in _context.StudentsCourses
                        join c in _context.Courses on sc.Course.CourseID equals c.CourseID
                        select new
                        {
                            c.Title,
                            c.CourseID
                        };

            //Group by the courses table by name and count
            var group = from x in query.ToList()
                        group x by x.Title into cat
                        select new
                        {
                            FirstName = cat.Key,
                            Num = cat.Count()
                        };

            //Insert the values in group to list of result
            foreach (var item in group)
            {
                Result Course = new Result();
                Course.State = item.FirstName;
                Course.freq = item.Num;


                CorsesGraph.Add(Course);
            }
            //return the list
            return Json(CorsesGraph);
        }


        //Students Graph Init
        public JsonResult StudentsGraphInit()
        {

            List<Result> StudentsGraph = new List<Result>();


            var query = from y in _context.Students
                        join l in _context.StudentsCourses on y.StudentID equals l.Student.StudentID
                        select new
                        {
                            y.FirstName,
                            y.StudentID
                        };
            //group for the graph
            var group = from x in query.ToList()
                        group x by x.FirstName into cat
                        select new
                        {
                            StudentName = cat.Key,
                            Num = cat.Count()
                        };

            foreach (var item in group)
            {
                Result numFoods = new Result();
                numFoods.State = item.StudentName;
                numFoods.freq = item.Num;
                StudentsGraph.Add(numFoods);
            }

            return Json(StudentsGraph);
        }

    }


   


}

src/TeachMe/Controllers/ReviewsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using TeachMe.Models;
using System;

namespace TeachMe.Controllers
{
    public class ReviewsController : Controller
    {
        private ApplicationDbContext _context;

        public ReviewsController(ApplicationDbContext context)
        {
            _context = context;    
        }




        // GET: Reviews
        public IActionResult Index()
        {
            var applicationDbContext = _context.Reviews.Include(r => r.Student);
            return View(applicationDbContext.ToList());
        }




        // GET: Reviews/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Review review = _context.Reviews.Single(m => m.ReviewID == id);
            if (review == null)
            {
                return HttpNotFound();
            }

            return View(review);
        }





        // GET: Reviews/Create
        public IActionResult Create()
        {
            ViewData["StudentID"] = new SelectList(_context.Students, "StudentID", "Student");
            return View();
        }






        // POST: Reviews/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Review review)
        {

            if (ModelState.IsValid)
            {
                DateTime now = DateTime.Now;
                review.Date = now;
                _context.Reviews.Add(review);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["StudentID"] = new SelectList(_context.Students, "StudentID", "Student", review.StudentID);
            return View(review);
        }





        // GET: Reviews/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Review review = _context.Reviews.Single(m => m.ReviewID == id);
            if (review == null)
            {
                return HttpNotFound();
            }
            ViewData["StudentID"] = new SelectList(_context.Students, "StudentID", "Student", review.StudentID);
            return View(review);
        }





        // POST: Reviews/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Update(review);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["StudentID"] = new SelectList(_context.Students, "StudentID", "Student", review.StudentID);
            return View(review);
        }

        // GET: Reviews/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Review review = _context.Reviews.Single(m => m.ReviewID == id);
            if (review == null)
            {
                return HttpNotFound();
            }

            return View(review);
        }





        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Review review = _context.Reviews.Single(m => m.ReviewID == id);
            _context.Reviews.Remove(review);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TeachMe/Controllers/RewardsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using TeachMe.Models;

namespace TeachMe.Controllers
{
    public class RewardsController : Controller
    {
        private ApplicationDbContext _context;

        public RewardsController(ApplicationDbContext context)
        {
            _context = context;    
        }
  



        // GET: Rewards
        public IActionResult Index()
        {
            return View(_context.Rewards.ToList());
        }




        // GET: Rewards/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Reward reward = _context.Rewards.Single(m => m.RewardID == id);
            if (reward == null)
            {
                return HttpNotFound();
            }

            return View(reward);
        }





        // GET: Rewards/Create
        public IActionResult Create()
        {
            return View();
        }





        // POST: Rewards/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Reward reward)
        {
            if (ModelState.IsValid)
            {
                _context.Rewards.Add(reward);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reward);
        }





        // GET: Rewards/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Reward reward = _context.Rewards.Single(m => m.RewardID == id);
            if (reward == null)
            {
                return HttpNotFound();
            }
            return View(reward);
        }





        // POST: Rewards/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Reward reward)
        {
            if (ModelState.IsValid)
            {
                _context.Update(reward);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reward);
        }





        // GET: Rewards/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Reward reward = _context.Rewards.Single(m => m.RewardID == id);
            if (reward == null)
            {
                return HttpNotFound();
            }

            return View(reward);
        }





        // POST: Rewards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Reward reward = _context.Rewards.Single(m => m.RewardID == id);
            _context.Rewards.Remove(reward);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/TeachMe/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<br /><br />
<h2>@ViewBag.Title</h2>
<hr />


<div class="contact">
    <b>Address: </b>
    <br />
    Kogel 67, Holon.
    <br /><br />


    <b>Phone: </b>
    0531234987
    <br />
    <b> Mail :</b>
    asiBela@gmail.com

    <br /><br />

    <b>Sunday-Thursday &nbsp;Friday</b>
    <br />
    09:00-21:00 &nbsp;&nbsp;09:00-15:00
</div>


<br />





<!--Google Maps-->
<div id="googleMap" style="width:1100px;height:400px;">

</div>

src/TeachMe/Views/Home/CoursesGraph.cshtml
@{
    ViewBag.Title = "Statistics";
}

<div align="center">

    <br />  <br />
    <div id="Headline">
        <h2>@ViewBag.Title</h2>
    </div>
    <h4 id="delete"><b>The number of students teaching the course</b></h4>


    <hr />

    <meta charset="utf-8">
    <style>
        body {
            width: 1260px;
            margin: 50px auto;
        }

        path {
            stroke: #fff;
        }

            path:hover {
                opacity: 0.9;
            }

        rect:hover {
            fill: lightblue;
        }

        .axis {
            font: 10px sans-serif;
        }

        .legend tr {
            border-bottom: 1px solid grey;
        }

            .legend tr:first-child {
                border-top: 1px solid grey;
            }

        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }

        .x.axis path {
            display: none;
        }

        .legend {
            margin-bottom: 76px;
            display: inline-block;
            border-collapse: collapse;
            border-spacing: 0px;
        }

            .legend td {
                padding: 4px 5px;
                vertical-align: bottom;
            }

        .legendFreq, .legendPerc {
            align: right;
            width: 50px;
        }
    </style>



    <div id='dashboard'></div>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script type="text/javascript">
        function dashboard(id, fData) {
            var barColor = 'blue';

            // compute total for each state.
            fData.forEach(function (d) { d.total = d.freq; });

            // function to handle histogram.
            function histoGram(fD) {
                var hG = {}, hGDim = { t: 40, r: 0, b: 30, l: 0 };
                hGDim.w = 1200 - hGDim.l - hGDim.r,
                hGDim.h = 600 - hGDim.t - hGDim.b;

                //create svg for histogram.
                var hGsvg = d3.select(id).append("svg")
                    .attr("width", hGDim.w + hGDim.l + hGDim.r)
                    .attr("height", hGDim.h + hGDim.t + hGDim.b).append("g")
                    .attr("transform", "translate(" + hGDim.l + "," + hGDim.t + ")");

                // create function for x-axis mapping.
                var x = d3.scale.ordinal().rangeRoundBands([0, hGDim.w], 0.1)
                        .domain(fD.map(function (d) { return d[0]; }));

                // Add x-axis to the histogram svg.
                hGsvg.append("g").attr("class", "x axis")
                    .attr("transform", "translate(0," + hGDim.h + ")")
                    .call(d3.svg.axis().scale(x).orient("bottom"));

                // Create function for y-axis map.
                var y = d3.scale.linear().range([hGDim.h, 0])
                        .domain([0, d3.max(fD, function (d) { return d[1]; })]);

                // Create bars for histogram to contain rectangles and freq labels.
                var bars = hGsvg.selectAll(".bar").data(fD).enter()
                        .append("g").attr("class", "bar");

                //create the rectangles.
                bars.append("rect")
                    .attr("x", function (d) { return x(d[0]); })
                    .attr("y", function (d) { return y(d[1]); })
                    .attr("width", x.rangeBand())
                    .attr("height", function (d) { return hGDim.h - y(d[1]); })
                    .attr('fill', barColor)
                    .on("mouseover", mouseover)// mouseover is defined below.
                    .on("mouseout", mouseout);// mouseout is defined below.

                //Create the frequency labels above the rectangles.
                bars.append("text").text(function (d) { return d3.format(",")(d[1]) })
                    .attr("x", function (d) { return x(d[0]) + x.rangeBand() / 2; })
                    .attr("y", function (d) { return y(d[1]) - 5; })
                    .attr("text-anchor", "middle");

                function mouseover(d) // utility function to be called on mouseover.
                {
                    // filter for selected state.
                    var st = fData.filter(function (s) { return s.State == d[0]; })[0],
                        nD = d3.keys(st.freq).map(function (s) { return { type: s, freq: st.freq[s] }; });
                }

                function mouseout(d) { }    // utility function to be called on mouseout.

                // create function to update the bars. This will be used by pie-chart.
                hG.update = function (nD, color) {
                    // update the domain of the y-axis map to reflect change in frequencies.
                    y.domain([0, d3.max(nD, function (d) { return d[1]; })]);

                    // Attach the new data to the bars.
                    var bars = hGsvg.selectAll(".bar").data(nD);

                    // transition the height and color of rectangles.
                    bars.select("rect").transition().duration(500)
                        .attr("y", function (d) { return y(d[1]); })
                        .attr("height", function (d) { return hGDim.h - y(d[1]); })
                        .attr("fill", color);

                    // transition the frequency labels location and change value.
                    bars.select("text").transition().duration(500)
                        .text(function (d) { return d3.format(",")(d[1]) })
                        .attr("y", function (d) { return y(d[1]) - 5; });
                }
                return hG;
            }


            // calculate total frequency by state for all segment.
            var sF = fData.map(function (d) { return [d.State, d.total]; });

            var hG = histoGram(sF); // create the histogram.

        }

        $.getJSON('/Home/CoursesGraphInit', function (data) {
            dashboard('#dashboard', data);
        });


    </script>
</div>

src/TeachMe/Views/Home/RewardsDetails.cshtml
@model IEnumerable<TeachMe.Models.Reward>
@using System.Security.Claims
@{

    ViewData["Title"] = "Our Rewards";
}
<br /><br />


<br /><br />
<div id="Headline">
    <h2>@ViewBag.Title</h2>
</div>
<hr />

<form asp-controller="Home" asp-action="RewardsDetails">
    <p>
        <i class="glyphicon glyphicon-search"></i>
        Reward Name: <input style="padding:0px" type="text" pattern="[a-zA-Z]{1,15}" title="letter  only" name="search">
        <input style="margin-left:30px" type="submit" value="search" />
    </p>
</form>

<div class="itemsReward">
    @foreach (var item in Model)
    {


            <div id="Head">
                <u> @Html.DisplayFor(modelItem => item.Title)</u>
            </div>
              <br />
            <p id="details">
                @Html.DisplayFor(modelItem => item.Description)
                <br />
                
                <div id="Jubot">Money:&nbsp @Html.DisplayFor(modelItem => item.NumOfJubot)</div>
                <br /><br />
            </p>
            <img src="@Html.DisplayFor(modelItem => item.Picture)" width="40%" height="40%">
             @if (item.Video != null)
             {
                 <video width="400" height="220" controls>
                     <source src="@Html.DisplayFor(modelItem => item.Video)" type="video/mp4">
                 </video>
              }

        @if (User.IsSignedIn())
        {
            @if (User.GetUserName().Equals("admin@gmail.com"))
            {
                <div>
                    <a asp-controller="Rewards" asp-action="Edit" asp-route-id="@item.RewardID">Edit</a> |
                    <a asp-controller="Rewards" asp-action="Details" asp-route-id="@item.RewardID">Details</a> |
                    <a asp-controller="Rewards" asp-action="Delete" asp-route-id="@item.RewardID">Delete</a>  |
                </div>
            }
        }
             


    }

</div>





<div class="dd">


  
</div>

src/TeachMe/Views/Home/StudentsReview.cshtml
@model IEnumerable<object>
@using System.Security.Claims

<link rel="stylesheet" href="~/css/Style.css" />
<link rel="stylesheet" href="~/scss/style.scss" />

@{
    List<TeachMe.Models.Student> students = Model.ToList()[0] as List<TeachMe.Models.Student>;
    List<TeachMe.Models.Review> reviews = Model.ToList()[1] as List<TeachMe.Models.Review>;
    ViewData["Title"] = "Students Review";
}
<br />  <br />
<div id="Headline">
    <h2>@ViewBag.Title</h2>
</div>
<hr />

<form asp-controller="Home" asp-action="Search" method="post">
    <div class="container" style="width:initial">
        <div class="row" style="width:auto; margin-bottom:15px">
            <div class="col-lg-3 col-md-6 col-md-offset-3 col-lg-offset-0">
                <div class="well" style="width:260px; height:400px; padding-top:2px; margin-left:120px">
                    <h3 align="center" style="padding:0px">Search Filter</h3>
                    <div class="form-group" style="align-content:center">
                        <label for="Name" class="control-label" style="padding-right:0px; padding-top:0px;">First Name</label>
                        <input type="text" class="control-label"  pattern="[a-zA-Z]{1,15}" title="letter  only" id="Name" aria-describedby="basic-addon1" name="Name" style="width:230px">
                    </div>
                    <div class="form-group">
                        <div class="form-group" style="align-content:center">
                            <label for="Address" class="form-group" style="padding-right:40px; padding-top:0px; width:140px">Address</label>
                            <input type="text" class="form-group" id="Address" pattern="[a-zA-Z]{1,15}" title="letter  only" aria-describedby="basic-addon1" name="Address" style="width:230px">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="jubot" class="control-label" style="padding-right:105px; padding-top:0px;">jubot</label>
                        <input type="number" min="0" step="1"class="form-group" id="jubot" aria-describedby="basic-addon1" name="jubot" style="width:230px">
                          
                    </div>
                    
                    <p class="text-center" style="padding:0px"><button type="submit" class="btn btn-danger glyphicon glyphicon-search" role="search"></button></p>
                </div>
            </div>
        </div>
    </div>
</form>
<br />


<div class="StudentReview">
    <div class="itemStu">
        @foreach (var item in students)
        {
            <div id="Head">
                
                Review For: @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)<br />
            </div>
            @foreach (var item1 in reviews.Where(m => m.StudentID == item.StudentID))
                {
                <div class="Review">
                    <div id="date">
                        @Html.DisplayFor(modelItem => item1.Date)
                    </div>
                    @Html.DisplayFor(modelItem => item1.Name) 
                    @for (int i = 0; i < (int)@item1.rate; i++)
                    {
                        <img src="~/images/v.png" width="2%" height="2%" />
                    }
                    :<br />
                    
                    
                    @Html.DisplayFor(modelItem => item1.Revieww).<br />
                    @if (User.IsSignedIn())
                    {
                        @if (User.GetUserName().Equals("admin@gmail.com"))
                        {
                            <div>
                                <a asp-controller="Reviews" asp-action="Edit" asp-route-id="@item1.ReviewID">Edit</a> |
                                <a asp-controller="Reviews" asp-action="Details" asp-route-id="@item1.ReviewID">Details</a> |
                                <a asp-controller="Reviews" asp-action="Delete" asp-route-id="@item1.ReviewID">Delete</a>  |
                            </div>
                        }
                    }
                    <br />
                </div>
            }
            <br />
        <!--POST-->
            <div id="PostComment">
                <form action="InsertReview" method="post" >
                    <div>Write a review</div>
                    <p>
                        <label for="Name">Name : </label>
                        <input name="Name" id="Name" type="text" pattern="[a-zA-Z]{1,15}" title="letter  only" required />
                    </p>
                    <p>
                        <label for="Revieww">Review : </label>
                        <input name="Revieww" id="Revieww" type="text" pattern="[a-zA-Z]{1,15}" title="letter  only" required />
                    </p>
                    <p>
                        Rating:
                        <label for="rate"></label>
                        <select class="form-control" placeholder="rate" name="rate" id="rate">
                            <option value="1">1 Star</option>
                            <option value="2">2 Star</option>
                            <option value="3">3 Star</option>
                            <option value="4">4 Star</option>
                            <option value="5">5 Star</option>
                        </select>
                    </p>
                   
                    <p><input type="hidden" pattern="[A-Za-z]" value="@item.StudentID" name="StudentID" /></p>
                    <p><input type="submit" value="Post review" /></p>
                </form>
                <br />
            </div>
        }
    </div>
</div>






@*<form action="Blog/InsertComment" method="post">
        <h3>Post a comment</h3>
        <p>
            <label for="Writer">Writer</label>
            <input name="Writer" id="Writer" type="text" required />
        </p>
        <p>
            <label for="Title">Title</label>
            <input name="Title" id="Title" type="text" required />
        </p>
        <p>
            <label for="Content">Content</label>
            <input name="Content" id="Content" type="text" required />
        </p>

        <p><input type="hidden" value="@item.StudentID" name="StudentID" /></p>
        <button>
            <p><input type="submit" value="Post comment" /></p>
        </button>
    </form>
*@